### ISSUE TITLE
Python script missing

### ISSUE THREAD

**Issue by SlytherinCz** [Arlington1985/dixons_test#1]
producer is attempting to execute `rabbitmqadmin.py` which is not present.

```
[2018-09-05 09:04:10] [99be2b5c-44cc-4507-986a-ed4c1e22ad2c] [INFO]    Generated JSON from parameters: {"release_number":"123","datetime":"2018-09-05 09:04:10"}
python: can't open file 'rabbitmqadmin.py': [Errno 2] No such file or directory
```

**Comment by Arlington1985** [comment]
@SlytherinCz , thanks for report. I have forgot to upload `rabbitmqadmin.py` file which I forgot to mention source of the file where it was downloaded([rabbitmqadmin](https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.7.7/bin/rabbitmqadmin)) Fixed now with uploading.

**Comment by Arlington1985** [comment]
@SlytherinCz , did your issue resolved?

**Comment by SlytherinCz** [comment]
@Arlington1985 yup, looks like it
